### ISSUE TITLE
Redesign the slideshow

### ISSUE THREAD

**Issue by oparoz** [nextcloud/gallery#59]
_From @oparoz on July 29, 2015 16:14_

If we stay with the current version of the slideshow, we need to fix and implement a few things. The alternative is to focus on something like Photoswipe https://github.com/owncloud/gallery/issues/158
### Must have
- [x] Show file name in the slideshow #237
- [ ] Show file actions in the slideshow (sharing, rename, favorite, delete. download is already there) #68
- [x] Make background colour switcher optional #226 
- [x] Make the slideshow controls work with a light background  #51
- [ ] Add full screen button in slideshow #252 
### Should have
- [ ] Mobile users should be able to "swipe" through photos instead of clicking on icons #141
- [ ] Automatically select an appropriate background colour based on the image's luminance #84 
### Could have
- [ ] Settings (something like minimal/advanced interface switch, etc.) #4 – if we feel we can not do it automatically
- [ ] Let the user rotate pictures which support EXIF #236 
- [ ] Add comments to slideshow #176
- [ ] Various picture transitions in the slideshow #83 
- [ ] Add HD option which would send the original pictures to the slideshow #193
##

_Copied from original issue: owncloud/gallery#255_

**Comment by oparoz** [comment]
@jancborchardt @demattin @setnes @libasys Feel free to add to the list if required.

**Comment by oparoz** [comment]
_From @libasys on July 29, 2015 16:43_

HD option is a good idea! Have you made a scribble for the redesign, how it could, should, incl. buttons?

**Comment by oparoz** [comment]
> Have you made a scribble for the redesign, how it could, should, incl. buttons?

I haven't, but @jancborchardt already has an idea of what it should look like. A mockup would be nice indeed :)
